esphome:
  name: "wigglemonitor"

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  
ota:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "..."
    password: "..."

light:
  - platform: monochromatic
    name: "WiggleMonitor Light"
    output: wiggleMonitorLight
    default_transition_length: 0s

output:
  - platform: rp2040_pwm
    id: wiggleMonitorLight
    pin: GPIO27

dallas:
  - pin: GPIO6

sensor:
  - platform: bme680
    temperature:
      name: "WiggleMonitor Temperature"
      oversampling: 16x
    pressure:
      name: "WiggleMonitor Pressure"
    humidity:
      name: "WiggleMonitor Humidity"
    gas_resistance:
      name: "WiggleMonitor Gas Resistance"
    address: 0x77
    update_interval: 60s
  - platform: dallas
    address: 0xe401131e5ee12a28
    name: "WiggleMonitor Soil Temperature"
  - platform: adc
    id: soil_moisture
    pin: GPIO26
    name: "WiggleMonitor Soil Moisture"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: 20s
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 1.48 -> 100.00
        - 2.8 -> 0.00
    - lambda: |
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);