esphome:
  name: "wigglecamera"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: GPIO4
  scl: GPIO13
  scan: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-A7Cbd0"
    password: "Vs0NsmefIgZi"

captive_portal:

output:
  - platform: ledc
    id: wiggleBinFlashLight
    pin: GPIO4

light:
  - platform: monochromatic
    name: "WiggleBin Flash Light"
    output: wiggleBinFlashLight
    default_transition_length: 0s
    
esp32_camera:
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  contrast: 1
  brightness: 1
  name: Wiggle Camera
